package com.ygy.model;

public class Springbootdb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column springbootDB.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column springbootDB.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column springbootDB.id
     *
     * @return the value of springbootDB.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column springbootDB.id
     *
     * @param id the value for springbootDB.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column springbootDB.name
     *
     * @return the value of springbootDB.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column springbootDB.name
     *
     * @param name the value for springbootDB.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }
}